# Generated by Django 4.2.4 on 2023-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='createdBy',
            new_name='sessionId',
        ),
        migrations.AlterField(
            model_name='message',
            name='createdOn',
            field=models.DateTimeField(),
        ),
    ]
